package CommunicationProtocol

/**
  * Created by robertMueller on 14.02.17.
  */
sealed trait Message
case class ClientMessage(message: String, user: String, autoGenerated: Boolean = false) extends Message
case class PrivateMessage(message: String, user: String, autoGenerated:Boolean) extends Message
case class PublicMessage(message: String, user: String, autoGenerated:Boolean) extends Message
case class BotMessage(message: String, user: String, autoGenerated:Boolean = true) extends Message
