package CommunicationProtocol

/**
  * Created by robertMueller on 14.02.17.
  */
sealed trait Message
case class ClientMessage(message: String, user: String, autoGenerated: Boolean = false) extends Message
case class ClientMessageWithRole(message: String, user: String, autoGenerated: Boolean = false, role: String = "student") extends Message {
  def asClientMessage = ClientMessage(this.message, this.user, this.autoGenerated)
}
case class PrivateMessage(message: String, user: String, autoGenerated:Boolean) extends Message
case class PublicMessage(message: String, user: String, autoGenerated:Boolean) extends Message
case class BotMessage(message: String, user: String, autoGenerated:Boolean = true) extends Message

